@startuml classes_Cellular
set namespaceSeparator none
class "CellularAutomataLevelGenerator" as CellularAutomataLevelGenerator.CellularAutomataLevelGenerator {
  fill_percent : float
  floor_char : str
  grid
  iterations : int
  wall_char : str
  generate(seed)
}
@enduml
