@startuml classes_gui
set namespaceSeparator none
class "BaseScene" as gui.core.base_scene.BaseScene {
  game
  {abstract}draw(screen)
  {abstract}handle_events(events)
  {abstract}update()
}
class "Button" as gui.utils.button.Button {
  callback
  font : Font
  hovered : bool
  rect
  text
  draw(screen)
  handle_event(event)
}
class "ControlBinding" as gui.game_states.options.ControlBinding {
  action
  font
  game
  label
  listening : bool
  pos
  rect
  draw(screen)
  handle_event(event)
}
class "Game" as gui.main.Game {
  clock
  scene_manager
  screen
  settings : dict
  run()
}
class "GameplayScene" as gui.game_states.gameplay.GameplayScene {
  draw(screen)
  handle_events(events)
  {abstract}update()
}
class "MenuScene" as gui.game_states.menu.MenuScene {
  buttons : list
  font : Font
  title_font : Font
  create_buttons()
  draw(screen)
  handle_events(events)
  open_options()
  quit_game()
  start_game()
  {abstract}update()
}
class "OptionsScene" as gui.game_states.options.OptionsScene {
  active_tab : str
  back_button
  control_bindings : list
  font : Font
  sound_sliders : list
  tabs : list
  video_sliders : list
  video_toggles : list
  draw(screen)
  go_back()
  handle_events(events)
  set_tab(tab_name)
  {abstract}update()
}
class "SceneManager" as gui.core.scene_manager.SceneManager {
  scene
  go_to(new_scene)
}
class "Slider" as gui.game_states.options.Slider {
  font
  game
  height : int
  key
  label
  max
  min
  pos
  slider_rect
  step
  width : int
  draw(screen)
  get_value()
  handle_event(event)
}
class "Toggle" as gui.game_states.options.Toggle {
  font
  game
  key
  label
  rect
  draw(screen)
  handle_event(event)
}
@enduml
